# Generated by Django 5.1 on 2025-03-24 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileInfo',
            new_name='NoteInfo',
        ),
    ]
